### ISSUE TITLE
Lcopt setup doesn't check the model's ecoinvent version.

### ISSUE THREAD

**Issue by haasad** [pjamesjoyce/lcopt#56]
Example; This is my config:
```
ecoinvent:
  password: ''
  system_model: cutoff
  username: ''
  version: '3.4'
model_storage:
  location: appdir
  project: single
  single_project_name: LCOPT_Models
```
I then run:
```python
model = lcopt.LcoptModel(load='/home/adrian/.local/share/Lcopt/models/ecoinvent_example.lcopt')
```
Assume the `LCOPT_Models`-project doesn't exist yet, or has been deleted. This will set up a project with ecoinvent cutoff 3.4 based on my config, even though `ecoinvent_example.lcopt` is based on cutoff 3.3. Ideally `lcopt.LcoptModel.__init__` should get the information about what database to use from the model to be loaded and set up the project accordingly.
